package br.com.maiscambio.util;

import org.springframework.http.MediaType;

public class MediaTypeHelper
{
	public static String getExtension(MediaType mediaType)
	{
		return getExtension(mediaType.toString());
	}
	
	public static String getExtension(String mediaType)
	{
		switch(mediaType.toLowerCase())
		{
			case "x-world/x-3dmf":
				return "3dm";
			case "application/octet-stream":
				return "a";
			case "application/x-authorware-bin":
				return "aab";
			case "application/x-authorware-map":
				return "aam";
			case "application/x-authorware-seg":
				return "aas";
			case "text/vnd.abc":
				return "abc";
			case "text/html":
				return "acgi";
			case "video/animaflex":
				return "afl";
			case "application/postscript":
				return "ai";
			case "audio/aiff":
				return "aif";
			case "audio/x-aiff":
				return "aif";
			case "application/x-aim":
				return "aim";
			case "text/x-audiosoft-intra":
				return "aip";
			case "application/x-navi-animation":
				return "ani";
			case "application/x-nokia-9000-communicator-add-on-software":
				return "aos";
			case "application/mime":
				return "aps";
			case "application/arj":
				return "arj";
			case "image/x-jg":
				return "art";
			case "video/x-ms-asf":
				return "asf";
			case "text/x-asm":
				return "asm";
			case "text/asp":
				return "asp";
			case "application/x-mplayer2":
				return "asx";
			case "video/x-ms-asf-plugin":
				return "asx";
			case "audio/basic":
				return "au";
			case "audio/x-au":
				return "au";
			case "application/x-troff-msvideo":
				return "avi";
			case "video/avi":
				return "avi";
			case "video/msvideo":
				return "avi";
			case "video/x-msvideo":
				return "avi";
			case "video/avs-video":
				return "avs";
			case "application/x-bcpio":
				return "bcpio";
			case "application/mac-binary":
				return "bin";
			case "application/macbinary":
				return "bin";
			case "application/x-binary":
				return "bin";
			case "application/x-macbinary":
				return "bin";
			case "image/bmp":
				return "bm";
			case "image/x-windows-bmp":
				return "bmp";
			case "application/book":
				return "boo";
			case "application/x-bzip2":
				return "boz";
			case "application/x-bsh":
				return "bsh";
			case "application/x-bzip":
				return "bz";
			case "text/plain":
				return "c";
			case "text/x-c":
				return "c";
			case "application/vnd.ms-pki.seccat":
				return "cat";
			case "application/clariscad":
				return "ccad";
			case "application/x-cocoa":
				return "cco";
			case "application/cdf":
				return "cdf";
			case "application/x-cdf":
				return "cdf";
			case "application/x-netcdf":
				return "cdf";
			case "application/pkix-cert":
				return "cer";
			case "application/x-x509-ca-cert":
				return "cer";
			case "application/x-chat":
				return "cha";
			case "application/java":
				return "class";
			case "application/java-byte-code":
				return "class";
			case "application/x-java-class":
				return "class";
			case "application/x-cpio":
				return "cpio";
			case "application/mac-compactpro":
				return "cpt";
			case "application/x-compactpro":
				return "cpt";
			case "application/x-cpt":
				return "cpt";
			case "application/pkcs-crl":
				return "crl";
			case "application/pkix-crl":
				return "crl";
			case "application/x-x509-user-cert":
				return "crt";
			case "application/x-csh":
				return "csh";
			case "text/x-script.csh":
				return "csh";
			case "application/x-pointplus":
				return "css";
			case "text/css":
				return "css";
			case "application/x-director":
				return "dcr";
			case "application/x-deepv":
				return "deepv";
			case "video/x-dv":
				return "dif";
			case "video/dl":
				return "dl";
			case "video/x-dl":
				return "dl";
			case "application/msword":
				return "doc";
			case "application/commonground":
				return "dp";
			case "application/drafting":
				return "drw";
			case "application/x-dvi":
				return "dvi";
			case "drawing/x-dwf (old)":
				return "dwf";
			case "model/vnd.dwf":
				return "dwf";
			case "application/acad":
				return "dwg";
			case "image/vnd.dwg":
				return "dwg";
			case "image/x-dwg":
				return "dwg";
			case "application/dxf":
				return "dxf";
			case "text/x-script.elisp":
				return "el";
			case "application/x-bytecode.elisp (compiled elisp)":
				return "elc";
			case "application/x-elc":
				return "elc";
			case "application/x-envoy":
				return "env";
			case "application/x-esrehber":
				return "es";
			case "text/x-setext":
				return "etx";
			case "application/envoy":
				return "evy";
			case "text/x-fortran":
				return "f";
			case "application/vnd.fdf":
				return "fdf";
			case "application/fractals":
				return "fif";
			case "image/fif":
				return "fif";
			case "video/fli":
				return "fli";
			case "video/x-fli":
				return "fli";
			case "image/florian":
				return "flo";
			case "text/vnd.fmi.flexstor":
				return "flx";
			case "video/x-atomic3d-feature":
				return "fmf";
			case "image/vnd.fpx":
				return "fpx";
			case "image/vnd.net-fpx":
				return "fpx";
			case "application/freeloader":
				return "frl";
			case "audio/make":
				return "funk";
			case "image/g3fax":
				return "g3";
			case "image/gif":
				return "gif";
			case "video/gl":
				return "gl";
			case "video/x-gl":
				return "gl";
			case "audio/x-gsm":
				return "gsd";
			case "application/x-gsp":
				return "gsp";
			case "application/x-gss":
				return "gss";
			case "application/x-gtar":
				return "gtar";
			case "application/x-compressed":
				return "gz";
			case "application/x-gzip":
				return "gz";
			case "multipart/x-gzip":
				return "gzip";
			case "text/x-h":
				return "h";
			case "application/x-hdf":
				return "hdf";
			case "application/x-helpfile":
				return "help";
			case "application/vnd.hp-hpgl":
				return "hgl";
			case "text/x-script":
				return "hlb";
			case "application/hlp":
				return "hlp";
			case "application/x-winhelp":
				return "hlp";
			case "application/binhex":
				return "hqx";
			case "application/binhex4":
				return "hqx";
			case "application/mac-binhex":
				return "hqx";
			case "application/mac-binhex40":
				return "hqx";
			case "application/x-binhex40":
				return "hqx";
			case "application/x-mac-binhex40":
				return "hqx";
			case "application/hta":
				return "hta";
			case "text/x-component":
				return "htc";
			case "text/webviewhtml":
				return "htt";
			case "x-conference/x-cooltalk":
				return "ice";
			case "image/x-icon":
				return "ico";
			case "image/ief":
				return "ief";
			case "application/iges":
				return "iges";
			case "model/iges":
				return "iges";
			case "application/x-ima":
				return "ima";
			case "application/x-httpd-imap":
				return "imap";
			case "application/inf":
				return "inf";
			case "application/x-internett-signup":
				return "ins";
			case "application/x-ip2":
				return "ip";
			case "video/x-isvideo":
				return "isu";
			case "audio/it":
				return "it";
			case "application/x-inventor":
				return "iv";
			case "i-world/i-vrml":
				return "ivr";
			case "application/x-livescreen":
				return "ivy";
			case "audio/x-jam":
				return "jam";
			case "text/x-java-source":
				return "jav";
			case "application/x-java-commerce":
				return "jcm";
			case "image/jpeg":
				return "jpg";
			case "image/pjpeg":
				return "jpg";
			case "image/x-jps":
				return "jps";
			case "application/x-javascript":
				return "js";
			case "application/javascript":
				return "js";
			case "application/ecmascript":
				return "js";
			case "text/javascript":
				return "js";
			case "text/ecmascript":
				return "js";
			case "image/jutvision":
				return "jut";
			case "audio/midi":
				return "kar";
			case "music/x-karaoke":
				return "kar";
			case "application/x-ksh":
				return "ksh";
			case "text/x-script.ksh":
				return "ksh";
			case "audio/nspaudio":
				return "la";
			case "audio/x-nspaudio":
				return "la";
			case "audio/x-liveaudio":
				return "lam";
			case "application/x-latex":
				return "latex";
			case "application/lha":
				return "lha";
			case "application/x-lha":
				return "lha";
			case "application/x-lisp":
				return "lsp";
			case "text/x-script.lisp":
				return "lsp";
			case "text/x-la-asf":
				return "lsx";
			case "application/x-lzh":
				return "lzh";
			case "application/lzx":
				return "lzx";
			case "application/x-lzx":
				return "lzx";
			case "text/x-m":
				return "m";
			case "video/mpeg":
				return "m1v";
			case "audio/mpeg":
				return "m2a";
			case "audio/x-mpequrl":
				return "m3u";
			case "application/x-troff-man":
				return "man";
			case "application/x-navimap":
				return "map";
			case "application/mbedlet":
				return "mbd";
			case "application/x-magic-cap-package-1.0":
				return "mc$";
			case "application/mcad":
				return "mcd";
			case "application/x-mathcad":
				return "mcd";
			case "image/vasa":
				return "mcf";
			case "text/mcf":
				return "mcf";
			case "application/netmc":
				return "mcp";
			case "application/x-troff-me":
				return "me";
			case "message/rfc822":
				return "mht";
			case "application/x-midi":
				return "mid";
			case "audio/x-mid":
				return "mid";
			case "audio/x-midi":
				return "mid";
			case "music/crescendo":
				return "mid";
			case "x-music/x-midi":
				return "mid";
			case "application/x-frame":
				return "mif";
			case "application/x-mif":
				return "mif";
			case "www/mime":
				return "mime";
			case "audio/x-vnd.audioexplosion.mjuicemediafile":
				return "mjf";
			case "video/x-motion-jpeg":
				return "mjpg";
			case "application/base64":
				return "mm";
			case "application/x-meme":
				return "mm";
			case "audio/mod":
				return "mod";
			case "audio/x-mod":
				return "mod";
			case "video/quicktime":
				return "moov";
			case "video/x-sgi-movie":
				return "movie";
			case "audio/x-mpeg":
				return "mp2";
			case "video/x-mpeg":
				return "mp2";
			case "video/x-mpeq2a":
				return "mp2";
			case "audio/mpeg3":
				return "mp3";
			case "audio/x-mpeg-3":
				return "mp3";
			case "application/x-project":
				return "mpc";
			case "application/vnd.ms-project":
				return "mpp";
			case "application/marc":
				return "mrc";
			case "application/x-troff-ms":
				return "ms";
			case "application/x-vnd.audioexplosion.mzz":
				return "mzz";
			case "image/naplps":
				return "nap";
			case "application/vnd.nokia.configuration-message":
				return "ncm";
			case "image/x-niff":
				return "nif";
			case "application/x-mix-transfer":
				return "nix";
			case "application/x-conference":
				return "nsc";
			case "application/x-navidoc":
				return "nvd";
			case "application/oda":
				return "oda";
			case "application/x-omc":
				return "omc";
			case "application/x-omcdatamaker":
				return "omcd";
			case "application/x-omcregerator":
				return "omcr";
			case "text/x-pascal":
				return "p";
			case "application/pkcs10":
				return "p10";
			case "application/x-pkcs10":
				return "p10";
			case "application/pkcs-12":
				return "p12";
			case "application/x-pkcs12":
				return "p12";
			case "application/x-pkcs7-signature":
				return "p7a";
			case "application/pkcs7-mime":
				return "p7c";
			case "application/x-pkcs7-mime":
				return "p7c";
			case "application/x-pkcs7-certreqresp":
				return "p7r";
			case "application/pkcs7-signature":
				return "p7s";
			case "application/pro_eng":
				return "part";
			case "text/pascal":
				return "pas";
			case "image/x-portable-bitmap":
				return "pbm";
			case "application/vnd.hp-pcl":
				return "pcl";
			case "application/x-pcl":
				return "pcl";
			case "image/x-pict":
				return "pct";
			case "image/x-pcx":
				return "pcx";
			case "chemical/x-pdb":
				return "pdb";
			case "application/pdf":
				return "pdf";
			case "audio/make.my.funk":
				return "pfunk";
			case "image/x-portable-graymap":
				return "pgm";
			case "image/x-portable-greymap":
				return "pgm";
			case "image/pict":
				return "pic";
			case "application/x-newton-compatible-pkg":
				return "pkg";
			case "application/vnd.ms-pki.pko":
				return "pko";
			case "text/x-script.perl":
				return "pl";
			case "application/x-pixclscript":
				return "plx";
			case "image/x-xpixmap":
				return "pm";
			case "text/x-script.perl-module":
				return "pm";
			case "application/x-pagemaker":
				return "pm4";
			case "image/png":
				return "png";
			case "application/x-portable-anymap":
				return "pnm";
			case "image/x-portable-anymap":
				return "pnm";
			case "application/mspowerpoint":
				return "pot";
			case "application/vnd.ms-powerpoint":
				return "pot";
			case "model/x-pov":
				return "pov";
			case "image/x-portable-pixmap":
				return "ppm";
			case "application/powerpoint":
				return "ppt";
			case "application/x-mspowerpoint":
				return "ppt";
			case "application/x-freelance":
				return "pre";
			case "paleovu/x-pv":
				return "pvu";
			case "text/x-script.phyton":
				return "py";
			case "applicaiton/x-bytecode.python":
				return "pyc";
			case "audio/vnd.qcelp":
				return "qcp";
			case "image/x-quicktime":
				return "qif";
			case "video/x-qtc":
				return "qtc";
			case "audio/x-pn-realaudio":
				return "ra";
			case "audio/x-pn-realaudio-plugin":
				return "ra";
			case "audio/x-realaudio":
				return "ra";
			case "application/x-cmu-raster":
				return "ras";
			case "image/cmu-raster":
				return "ras";
			case "image/x-cmu-raster":
				return "ras";
			case "text/x-script.rexx":
				return "rexx";
			case "image/vnd.rn-realflash":
				return "rf";
			case "image/x-rgb":
				return "rgb";
			case "application/vnd.rn-realmedia":
				return "rm";
			case "audio/mid":
				return "rmi";
			case "application/ringing-tones":
				return "rng";
			case "application/vnd.nokia.ringing-tone":
				return "rng";
			case "application/vnd.rn-realplayer":
				return "rnx";
			case "application/x-troff":
				return "roff";
			case "image/vnd.rn-realpix":
				return "rp";
			case "text/richtext":
				return "rt";
			case "text/vnd.rn-realtext":
				return "rt";
			case "application/rtf":
				return "rtf";
			case "application/x-rtf":
				return "rtf";
			case "video/vnd.rn-realvideo":
				return "rv";
			case "audio/s3m":
				return "s3m";
			case "application/x-tbook":
				return "sbk";
			case "application/x-lotusscreencam":
				return "scm";
			case "text/x-script.guile":
				return "scm";
			case "text/x-script.scheme":
				return "scm";
			case "video/x-scm":
				return "scm";
			case "application/sdp":
				return "sdp";
			case "application/x-sdp":
				return "sdp";
			case "application/sounder":
				return "sdr";
			case "application/sea":
				return "sea";
			case "application/x-sea":
				return "sea";
			case "application/set":
				return "set";
			case "text/sgml":
				return "sgm";
			case "text/x-sgml":
				return "sgm";
			case "application/x-sh":
				return "sh";
			case "application/x-shar":
				return "sh";
			case "text/x-script.sh":
				return "sh";
			case "text/x-server-parsed-html":
				return "shtml";
			case "audio/x-psid":
				return "sid";
			case "application/x-sit":
				return "sit";
			case "application/x-stuffit":
				return "sit";
			case "application/x-koan":
				return "skd";
			case "application/x-seelogo":
				return "sl";
			case "application/smil":
				return "smi";
			case "audio/x-adpcm":
				return "snd";
			case "application/solids":
				return "sol";
			case "application/x-pkcs7-certificates":
				return "spc";
			case "text/x-speech":
				return "spc";
			case "application/futuresplash":
				return "spl";
			case "application/x-sprite":
				return "spr";
			case "application/x-wais-source":
				return "src";
			case "application/streamingmedia":
				return "ssm";
			case "application/vnd.ms-pki.certstore":
				return "sst";
			case "application/step":
				return "step";
			case "application/sla":
				return "stl";
			case "application/vnd.ms-pki.stl":
				return "stl";
			case "application/x-navistyle":
				return "stl";
			case "application/x-sv4cpio":
				return "sv4cpio";
			case "application/x-sv4crc":
				return "sv4crc";
			case "application/x-world":
				return "svr";
			case "x-world/x-svr":
				return "svr";
			case "application/x-shockwave-flash":
				return "swf";
			case "application/x-tar":
				return "tar";
			case "application/toolbook":
				return "tbk";
			case "application/x-tcl":
				return "tcl";
			case "text/x-script.tcl":
				return "tcl";
			case "text/x-script.tcsh":
				return "tcsh";
			case "application/x-tex":
				return "tex";
			case "application/x-texinfo":
				return "texi";
			case "application/plain":
				return "text";
			case "application/gnutar":
				return "tgz";
			case "image/tiff":
				return "tif";
			case "image/x-tiff":
				return "tif";
			case "audio/tsp-audio":
				return "tsi";
			case "application/dsptype":
				return "tsp";
			case "audio/tsplayer":
				return "tsp";
			case "text/tab-separated-values":
				return "tsv";
			case "text/x-uil":
				return "uil";
			case "text/uri-list":
				return "uni";
			case "application/i-deas":
				return "unv";
			case "application/x-ustar":
				return "ustar";
			case "multipart/x-ustar":
				return "ustar";
			case "text/x-uuencode":
				return "uu";
			case "application/x-cdlink":
				return "vcd";
			case "text/x-vcalendar":
				return "vcs";
			case "application/vda":
				return "vda";
			case "video/vdo":
				return "vdo";
			case "application/groupwise":
				return "vew";
			case "video/vivo":
				return "viv";
			case "video/vnd.vivo":
				return "viv";
			case "application/vocaltec-media-desc":
				return "vmd";
			case "application/vocaltec-media-file":
				return "vmf";
			case "audio/voc":
				return "voc";
			case "audio/x-voc":
				return "voc";
			case "video/vosaic":
				return "vos";
			case "audio/voxware":
				return "vox";
			case "audio/x-twinvq-plugin":
				return "vqe";
			case "audio/x-twinvq":
				return "vqf";
			case "application/x-vrml":
				return "vrml";
			case "model/vrml":
				return "vrml";
			case "x-world/x-vrml":
				return "vrml";
			case "x-world/x-vrt":
				return "vrt";
			case "application/x-visio":
				return "vsd";
			case "application/wordperfect6.0":
				return "w60";
			case "application/wordperfect6.1":
				return "w61";
			case "audio/wav":
				return "wav";
			case "audio/x-wav":
				return "wav";
			case "application/x-qpro":
				return "wb1";
			case "image/vnd.wap.wbmp":
				return "wbmp";
			case "application/vnd.xara":
				return "web";
			case "application/x-123":
				return "wk1";
			case "windows/metafile":
				return "wmf";
			case "text/vnd.wap.wml":
				return "wml";
			case "application/vnd.wap.wmlc":
				return "wmlc";
			case "text/vnd.wap.wmlscript":
				return "wmls";
			case "application/vnd.wap.wmlscriptc":
				return "wmlsc";
			case "application/wordperfect":
				return "wp";
			case "application/x-wpwin":
				return "wpd";
			case "application/x-lotus":
				return "wq1";
			case "application/mswrite":
				return "wri";
			case "application/x-wri":
				return "wri";
			case "text/scriplet":
				return "wsc";
			case "application/x-wintalk":
				return "wtk";
			case "image/x-xbitmap":
				return "xbm";
			case "image/x-xbm":
				return "xbm";
			case "image/xbm":
				return "xbm";
			case "video/x-amt-demorun":
				return "xdr";
			case "xgl/drawing":
				return "xgz";
			case "image/vnd.xiff":
				return "xif";
			case "application/excel":
				return "xl";
			case "application/x-excel":
				return "xla";
			case "application/x-msexcel":
				return "xla";
			case "application/vnd.ms-excel":
				return "xlb";
			case "audio/xm":
				return "xm";
			case "application/xml":
				return "xml";
			case "text/xml":
				return "xml";
			case "xgl/movie":
				return "xmz";
			case "application/x-vnd.ls-xpix":
				return "xpix";
			case "image/xpm":
				return "xpm";
			case "video/x-amt-showrun":
				return "xsr";
			case "image/x-xwd":
				return "xwd";
			case "image/x-xwindowdump":
				return "xwd";
			case "application/x-compress":
				return "z";
			case "application/x-zip-compressed":
				return "zip";
			case "application/zip":
				return "zip";
			case "multipart/x-zip":
				return "zip";
			case "text/x-script.zsh":
				return "zsh";
			default:
				return null;
		}
	}
}
